/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import {
  CircuitZKit,
  CircuitZKitConfig,
  Groth16Proof,
  PlonkProof,
  Groth16ProofPoints,
  PlonkProofPoints,
  NumberLike,
  NumericString,
  PublicSignals,
  Groth16Implementer,
  PlonkImplementer,
} from "@solarity/zkit";

import { normalizePublicSignals, denormalizePublicSignals } from "../helpers";

export type PrivateMultiplierGroth16 = {
  a: NumberLike;
  b: NumberLike;
};

export type PublicMultiplierGroth16 = {
  c: NumberLike;
};

export type ProofMultiplierGroth16 = {
  proof: Groth16Proof;
  publicSignals: PublicMultiplierGroth16;
};

export type CalldataMultiplierGroth16 = {
  proofPoints: Groth16ProofPoints;
  publicSignals: [NumericString];
};

export type QualifiedSignalNames =
  | "main.c"
  | "main.a"
  | "main.b"
  | "main.aCheck.inMinusOne"
  | "main.aCheck.inMinusOneInv"
  | "main.bCheck.inMinusOne"
  | "main.bCheck.inMinusOneInv";

export class Multiplier extends CircuitZKit<"groth16"> {
  constructor(config: CircuitZKitConfig) {
    super(config, new Groth16Implementer());
  }

  public async generateProof(
    inputs: PrivateMultiplierGroth16,
    witnessOverrides?: Partial<Record<QualifiedSignalNames, bigint>>,
  ): Promise<ProofMultiplierGroth16> {
    const proof = await super.generateProof(inputs as any, witnessOverrides);

    return {
      proof: proof.proof,
      publicSignals: this._normalizePublicSignals(proof.publicSignals),
    };
  }

  public async calculateWitness(
    inputs: PrivateMultiplierGroth16,
    witnessOverrides?: Partial<Record<QualifiedSignalNames, bigint>>,
  ): Promise<bigint[]> {
    return super.calculateWitness(inputs as any, witnessOverrides);
  }

  public async verifyProof(proof: ProofMultiplierGroth16): Promise<boolean> {
    return super.verifyProof({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public async generateCalldata(
    proof: ProofMultiplierGroth16,
  ): Promise<CalldataMultiplierGroth16> {
    return super.generateCalldata({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public getSignalNames(): string[] {
    return ["c"];
  }

  public getSignalDimensions(name: string): number[] {
    switch (name) {
      case "c":
        return [];
      default:
        throw new Error(`Unknown signal name: ${name}`);
    }
  }

  private _normalizePublicSignals(
    publicSignals: PublicSignals,
  ): PublicMultiplierGroth16 {
    return normalizePublicSignals(
      publicSignals,
      this.getSignalNames(),
      this.getSignalDimensions,
    );
  }

  private _denormalizePublicSignals(
    publicSignals: PublicMultiplierGroth16,
  ): PublicSignals {
    return denormalizePublicSignals(publicSignals, this.getSignalNames());
  }
}

export default Multiplier;
